# Generated by Django 3.1.3 on 2020-11-30 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('department', models.CharField(choices=[('CSE', 'CS'), ('IT', 'IT'), ('ECE', 'EC'), ('EEE', 'EE'), ('CIVIL', 'CVL'), ('MECH', 'ME')], max_length=10)),
                ('nationality', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('pic', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_ssc', models.CharField(max_length=3)),
                ('marks_inter', models.CharField(max_length=3)),
                ('registers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.registermodel')),
            ],
        ),
    ]
